# Lesson 01

## Lesson Objectives
* Understand what is NumPy and its **importance** for Data Science
* Experiment with array **builtin methods**
* Use array **methods and attributes**

<img src="https://raw.githubusercontent.com/numpy/numpy/181f273a59744d58f90f45d953a3285484c72cba/branding/logo/primary/numpylogo.svg" width="25%" height="25%" />

* NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
* It is a **Linear Algebra** Library and almost all of the libraries used in Data Science rely on NumPy as one of their main building blocks.

## Import Package

* Colab offers a session with a set of packages already installed. To check which packages are installed type in a code cell **!pip freeze** and run it. In case NumPy is not installed, you may type and run in a code cell **!pip install numpy**
* NumPy should be already incluced in this set of packages. You will just need to import it.

In [ ]:
import numpy as np

## Array

* An **array** is the foundation of NumPy and come as vector or matrix, where vector is a 1-d array, and matrix is 2-d (or n dimension) array. A matrix can also have have 1 row x 1 column.
* We can create a 1-d array based on a list:


In [ ]:
my_list = [7,9,88,4621]
my_list

In [ ]:
arr = np.array(my_list)
arr

* In the previous example, please note 1 bracket before the first item. That indicates it is a **1-d array**. 


```
array([   7,    9,   88, 4621])
```



* Just a side note
  * You don't have necessarily to pass the list as a variable at np.array() function, 
  * You can write the list directly if you prefer: np.array([7,9,88,4621])
  * Both create the same array

* An array can handle numbers, categories or both

In [ ]:
my_list = ['text','label_example',55,150,'final_text_example']
arr = np.array(my_list)
arr

* If your list has more than 1 dimension, you can create a 2-d array, or matrix


In [ ]:
my_matrix = [[10,80,77],[99,99,99],[0.5,0.6,0.75]]
arr = np.array(my_matrix)
arr

* In the previous example, please note the 2 brackets before the first item. That indicates it is a **2-d array**. 


```
array([[10.  , 8   .......
```



## Built in methods to generate arrays

* You can generate data for your arrays using builtin methods

In [ ]:
arr = np.arange(start=1,stop=9,step=1)
arr

* Text explaining something

In [ ]:
arr = np.zeros((2,2))
arr

* Text explaining something

In [ ]:
arr = np.zeros((2,2,2))
arr

* In the previous example, please note the 3 brackets before the first item. That indicates it is a **3-d array**. 


```
array([[[0.,    .......
```



* Text explaining something

In [ ]:
arr = np.ones((2,5))
arr

* Text explaining something

In [ ]:
arr = np.eye(3)
arr

* Text explaining something

In [ ]:
arr = np.linspace(start=1,stop=50,num=40)
arr

* Text explaining something

In [ ]:
arr = np.random.rand(2,2)
arr

* Text explaining something

In [ ]:
arr = np.random.randint(low=10,high=50,size=5)
arr 

* Text explaining something

In [ ]:
np.random.seed(seed=0)

## Array Methods

* Text explaining something

In [ ]:
arr = np.random.randint(low=1,high=150,size=40)
arr

In [ ]:
arr.reshape(4,10)

In [ ]:
arr.max()

In [ ]:
arr.argmax()

In [ ]:
arr.min()

In [ ]:
arr.argmin()

## Array Attributes

In [ ]:
arr.shape  # .shape is a attribute

In [ ]:
arr.dtype

## Activities

* Create in the cell below a 4 x 5 array of all the even integers from -6 to 32, including 32

In [114]:
arr = np.arange(start=-6,stop=33,step=2).reshape(4,5)
arr

array([[-6, -4, -2,  0,  2],
       [ 4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32]])

* Using your NumPy knowledge, print statment and displaying variables in a f-string, create the following statement:
  * "The max value for the array is 32 and its index location is 19"

In [115]:
print(f"The max value for the array is {arr.max()} and its index location is {arr.argmax()}")

The max value for the array is 32 and its index location is 19


# Lesson 02

## Lesson Objectives
* xxx
* xxxxx
* xx

<img src="https://raw.githubusercontent.com/numpy/numpy/181f273a59744d58f90f45d953a3285484c72cba/branding/logo/primary/numpylogo.svg" width="25%" height="25%" />

## Import Package

* Colab offers a session with a set of packages already installed. To check which packages are installed type in a code cell **!pip freeze** and run it. In case NumPy is not installed, you may type and run in a code cell **!pip install numpy**
* NumPy should be already incluced in this set of packages. You will just need to import it.

In [ ]:
import numpy as np

## Array Indexing and Selecting

In [ ]:
#Creating sample array
arr = arr = np.arange(0,21,2)
arr 

In [ ]:
#Get a value at an index
arr[8]

In [ ]:
#Get values in a range
arr[1:5]

In [ ]:
#Get values in a range
arr[:5]

In [ ]:
#Get values in a range
arr[1:]

In [ ]:
#Get values in a range
arr[:]

## Broadcast

In [ ]:
arr = np.arange(0,21,2)
slice_of_arr = arr[0:6]
slice_of_arr

In [ ]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

In [ ]:
arr # original array change as well!!!!

# the data is not copied, it was just a view. It helps to save memory

In [ ]:
# to create a independent slice_of_arr you should
arr = arr = np.arange(0,21,2)
slice_of_arr = arr[0:6].copy()
slice_of_arr



In [ ]:
slice_of_arr[:]=99
slice_of_arr  # slice_of_arr was changed

In [ ]:
arr  # original array remains the same

## Indexing a 2D array

In [ ]:
arr = np.random.randint(low=10,high=50,size=15).reshape(3,5)
arr

In [ ]:
#Indexing row
arr[1]

In [ ]:
# Getting individual element value
arr[1,0]

In [ ]:
# 2D array slicing rows and columns
arr[:2,1:]

## Selecting an array

In [ ]:
np.random.seed(seed=10)
arr = np.random.randint(low=1,high=25,size=15).reshape(3,5)
arr

In [ ]:
arr > 10

In [ ]:
arr[arr>10]

# Lesson 03

## Lesson Objectives
* xxxx
* xxxx
* xxxx

<img src="https://raw.githubusercontent.com/numpy/numpy/181f273a59744d58f90f45d953a3285484c72cba/branding/logo/primary/numpylogo.svg" width="25%" height="25%" />

## Import Package

* Colab offers a session with a set of packages already installed. To check which packages are installed type in a code cell **!pip freeze** and run it. In case NumPy is not installed, you may type and run in a code cell **!pip install numpy**
* NumPy should be already incluced in this set of packages. You will just need to import it.

In [ ]:
import numpy as np

## Operations

In [ ]:
arr = np.random.randint(low=-3,high=25,size=15).reshape(3,5)
arr

In [ ]:
arr + arr


In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
# Just replaced with nan
arr/arr

In [ ]:
1/arr

In [ ]:
arr**3

## Universal Functions

In [ ]:
# https://numpy.org/doc/stable/reference/ufuncs.html

In [ ]:
arr = np.random.randint(low=-3,high=25,size=15).reshape(3,5)
arr

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
np.max(arr)

In [ ]:
np.sin(arr)

In [ ]:
np.log(arr)

In [ ]:
np.std(arr)

# Lesson 04 - Exercises

## Lesson Objectives
* xxxx
* xxxx
* xxxx

<img src="https://raw.githubusercontent.com/numpy/numpy/181f273a59744d58f90f45d953a3285484c72cba/branding/logo/primary/numpylogo.svg" width="25%" height="25%" />

## Import Package

* Colab offers a session with a set of packages already installed. To check which packages are installed type in a code cell **!pip freeze** and run it. In case NumPy is not installed, you may type and run in a code cell **!pip install numpy**
* NumPy should be already incluced in this set of packages. You will just need to import it.

In [ ]:
import numpy as np

In [ ]:
#### Create an array of 10 zeros 
np.zeros(10)

In [ ]:
#### Create an array of 10 ones
np.ones(10)

In [ ]:
#### Create an array of 10 fives
np.ones(10) * 5

In [ ]:
#### Create an array of 10 integers from 10 to 50
np.random.randint(10,50,10)

In [ ]:
#### Create an array of all the even integers from 10 to 50 (including 50)
np.arange(10,51,2)

In [ ]:
#### Create a 3x3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

In [ ]:
#### Create a 3x3 identity matrix
np.eye(3)

In [ ]:
#### Use NumPy to generate a random number between 0 and 1
np.random.rand(1)

In [ ]:
#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
arr = np.random.randn(500)

In [ ]:
import matplotlib.pyplot as plt
plt.hist(x=arr,bins=50);

In [ ]:
#### Create an array of 20 linearly spaced points between 0 and 1:
np.linspace(0,1,20)

In [ ]:
# Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:
mat = np.arange(1,26).reshape(5,5)
mat

In [ ]:
mat[2:,1:]

In [ ]:
mat[:3,1:2]


In [ ]:
#### Get the sum of all the values in mat
np.sum(mat)

In [ ]:
#### Get the standard deviation of the values in mat
np.std(mat)

In [ ]:
#### Get the sum of all the columns in mat
np.sum(mat,0)