# Numpy



<img src="https://numpy.org/images/logos/numpy.svg" width="250" height="205" />

* NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks. (**change text, since it was copied**)

## Import Package

* Colab offers a session with a set of packages already installed. To check which packages are installed type in a code cell **!pip freeze** and run it. In case numpy is not installed, you may type and run in a code cell **!pip install numpy**
* Numpy should be already incluced in this set of packages. You will just need to import it.

In [35]:
import numpy as np
np.random.seed(seed=0)

# Lesson 01

## Array

* explain

In [ ]:
my_list = [1,2,3]
my_list

arr = np.array(my_list)
arr

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix
arr = np.array(my_matrix)
arr

## Built in methods to generate arrays

In [ ]:
arr = np.arange(start=1,stop=9,step=1)
arr

In [ ]:
arr = np.zeros((3,5))
arr

In [ ]:
arr = np.ones((2,5))
arr

In [ ]:
arr = np.eye(5)
arr

In [ ]:
arr = np.linspace(start=1,stop=50,num=40)
arr

In [ ]:
arr = np.random.rand(2,2)
arr

In [ ]:
arr = np.random.randint(low=10,high=50,size=5)
arr 

## Array Methods

In [ ]:
arr = np.random.randint(low=1,high=150,size=40)
arr

In [ ]:
arr.reshape(4,10)

In [ ]:
arr.max()

In [ ]:
arr.argmax()

In [ ]:
arr.min()

In [ ]:
arr.argmin()

## Array Attributes

In [ ]:
arr.shape  # .shape is a attribute

In [ ]:
arr.dtype

# Lesson 02

## Array Indexing and Selecting

In [11]:
#Creating sample array
arr = arr = np.arange(0,21,2)
arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
#Get a value at an index
arr[8]

16

In [13]:
#Get values in a range
arr[1:5]

array([2, 4, 6, 8])

In [14]:
#Get values in a range
arr[:5]

array([0, 2, 4, 6, 8])

In [16]:
#Get values in a range
arr[1:]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
#Get values in a range
arr[:]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## Broadcast

In [22]:
arr = np.arange(0,21,2)
slice_of_arr = arr[0:6]
slice_of_arr

array([ 0,  2,  4,  6,  8, 10])

In [23]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [25]:
arr # original array change as well!!!!

# the data is not copied, it was just a view. It helps to save memory

array([99, 99, 99, 99, 99, 99, 12, 14, 16, 18, 20])

In [26]:
# to create a independent slice_of_arr you should
arr = arr = np.arange(0,21,2)
slice_of_arr = arr[0:6].copy()
slice_of_arr



array([ 0,  2,  4,  6,  8, 10])

In [27]:
slice_of_arr[:]=99
slice_of_arr  # slice_of_arr was changed

array([99, 99, 99, 99, 99, 99])

In [28]:
arr  # original array remains the same

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## Indexing a 2D array

In [31]:
arr = np.random.randint(low=10,high=50,size=15).reshape(3,5)
arr

array([[40, 22, 40, 47, 21],
       [46, 18, 21, 29, 42],
       [17, 23, 15, 27, 37]])

In [32]:
#Indexing row
arr[1]

array([46, 18, 21, 29, 42])

In [33]:
# Getting individual element value
arr[1,0]

46

In [34]:
# 2D array slicing rows and columns
arr[:2,1:]

array([[22, 40, 47, 21],
       [18, 21, 29, 42]])

## Selecting an array

In [49]:
np.random.seed(seed=10)
arr = np.random.randint(low=1,high=25,size=15).reshape(3,5)
arr

array([[10,  5, 16,  1, 18],
       [17, 18,  9, 10,  1],
       [11,  9, 23,  5, 20]])

In [51]:
arr > 10

array([[False, False,  True, False,  True],
       [ True,  True, False, False, False],
       [ True, False,  True, False,  True]])

In [52]:
arr[arr>10]

array([16, 18, 17, 18, 11, 23, 20])

# Lesson 03

## Operations

In [53]:
arr = np.random.randint(low=1,high=25,size=15).reshape(3,5)
arr

array([[17,  5, 16, 12, 23],
       [12,  2,  9,  5, 15],
       [18, 20, 23, 14,  6]])