# Lesson 01

## Lesson Objectives
* Understand what is a NumPy **array**
* Experiment with array **builtin methods**
* Use array **methods and attributes**

<img src="https://raw.githubusercontent.com/numpy/numpy/181f273a59744d58f90f45d953a3285484c72cba/branding/logo/primary/numpylogo.svg" width="25%" height="25%" />

* NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
* It is a **Linear Algebra** Library and almost all of the libraries used in Data Science rely on NumPy as one of their main building blocks.

---

## Import Package

* Colab offers a session with a set of packages already installed. To check which packages are installed type in a code cell **!pip freeze** and run it. In case NumPy is not installed, you may type and run in a code cell **!pip install numpy**
* NumPy should be already incluced in this set of packages. You will just need to import it.

In [45]:
import numpy as np

---

## Array

* An **array** is the foundation of NumPy, it is defined as a grid of values, either numbers or not. It comes as vector or matrix, where vector is a 1-d array, and matrix is 2-d (or n dimension) array. A matrix can also have have 1 row x 1 column.
* An array is **useful** because it helps to organize data. With this structure, elements can easily be sorted or searched.
* We can create a 1-d array based on a list:


In [ ]:
my_list = [7,9,88,4621]
my_list

In [ ]:
arr = np.array(my_list)
arr

* In the previous example, please note 1 bracket before the first item. That indicates it is a **1-d array**. 


```
array([   7,    9,   88, 4621])
```



* Just a side note
  * You don't have necessarily to pass the list as a variable at np.array() function, 
  * You can write the list directly if you prefer: np.array([7,9,88,4621])
  * Both create the same array

* An array can **handle** numbers (integer, float etc), strings (text), timestamps (dates).

In [ ]:
my_list = ['text','label_example',55,150,'final_text_example']
arr = np.array(my_list)
arr

* If your list has more than 1 dimension, you can create a **2-d array**, or matrix.
* Please note the 2 brackets before the first item. That indicates it is a 2-d array.


In [ ]:
my_matrix = [[10,80,77], [99,99,99], ["this is good","string1","example"]]
my_matrix

In [ ]:
arr = np.array(my_matrix)
arr

---

## Built-in methods to generate arrays

* You can **generate data for your arrays** using built-in methods
* You can quickly create an **evenly spaced** array of numbers using np.arange(). 
    * You may provide 3 arguments: the start, stop and step size of values interval. 
    * Stop argument is not inclusive. 
    * Play around with different step to see the effect. You may try and see the effect with step as 0.5, 1, 2, and 5.

In [ ]:
arr = np.arange(start=1,stop=9,step=1)
arr

* You can also create an **array of zeros**. Just pass the shape of the desired array. The example below has a shape of 2 x 3 and is a 2-d array

In [ ]:
arr = np.zeros((2,3))
arr

* The example below has shape of 2 x 2 x 2 and is a 3-d array of zeros
* Please note the 3 brackets before the first item. That indicates it is a 3-d array.

In [ ]:
arr = np.zeros((2,2,3))
arr

* You could also create an **array of all ones**. The example below is a 2-d array.

In [ ]:
arr = np.ones((2,5))
arr

* You can also create **identity matrix**, that is a square matrix that has ones along its main diagonal and zeros everywhere else.
* The example below is an identity matrix of shape 4 x 4.

In [ ]:
arr = np.eye(4)
arr

* A similar function to np.arange() is **np.linspace()**, but instead of step argument, there is num argument. Num is the number of samples that need to be retrieved in that interval. 
  * You will provide as argument the start, end and how many points you want in between. 
  * Stop argument here is inclusive

In [ ]:
arr = np.linspace(start=1,stop=50,num=5)
arr

* You can also create an array of a given shape with **random values from 0 to 1 using np.random.rand()**
    * The arguments are the shape you are interested

In [ ]:
arr = np.random.rand(2,2)  # 2-d array
arr

In [ ]:
arr = np.random.rand(3,5,2) # 3-d array
arr

* You can also create an array of given shape from a **"standard normal" distribution using random.randn()**
* A standard normal distribution is a normal distribution with a mean of zero and standard deviation of 1. We will get back to that in future sections of the course

In [ ]:
arr = np.random.randn(8,2) # 2-d array
arr

In [ ]:
arr = np.random.randn(80) # 1-d array
arr

* You can also create random integers setting the interval and size using **np.random.randint()**
  * The arguments for interval are: low (inclusive) and high (exclusive). Size is the output shape, it can be an integer or tuple.

In [ ]:
arr = np.random.randint(low=10,high=50,size=5) # 1-d array
arr 

In [ ]:
arr = np.random.randint(low=250,high=888,size=(4,3)) # 2-d array
arr 

---

* You may be interested to generate "constant" random values
  * **Run the example below multiple times, the random values will change**

In [ ]:
arr = np.random.randint(low=10,high=50,size=5)
arr

* You need to set **numpy seed** in order to get constant random values
  * In a jupyter notebook code cell, you just have to add np.seed() before defining your array(s)
  * The argument is seed, a integer. You can set any integer
  * **Run multiple times the cell below and note the array values will be the same**

In [ ]:
np.random.seed(seed=123)
arr = np.random.randint(low=10,high=50,size=5)
arr

---

## Array Methods

* You can reshape the array without changing the data within it using  .reshape() method.
  * the example below shows a 1-d array, with shape 40. 

In [ ]:
np.random.seed(seed=0)
arr = np.random.randint(low=1,high=150,size=40)
arr

* You can reshape as 4 x 10, transforming into a 2-d array

In [ ]:
arr = arr.reshape(4,10)
arr

In [ ]:
arr.reshape(1,-1) #####

array([[ 48, 118,  68, 104,  10,  22,  37,  88,  71,  89]])

* There can be an opposite situation where you have a multidimensional array and want to transform to a 1-d array. You can use **flatten()** for it:

In [ ]:
np.random.seed(seed=0)
arr = np.random.randint(low=1,high=150,size=(2,5))
arr

array([[ 48, 118,  68, 104,  10],
       [ 22,  37,  88,  71,  89]])

In [ ]:
arr.flatten()

array([ 48, 118,  68, 104,  10,  22,  37,  88,  71,  89])

In [ ]:
arr.reshape(-1)

array([ 48, 118,  68, 104,  10,  22,  37,  88,  71,  89])

---

* Min and Max values can be acessed using .min() and .max() methods.

In [ ]:
arr.max()

In [ ]:
arr.min()

* You can determine the index position of the minimum or maximum value in the darray along a particular axis using the argmin() and argmax() methods

In [ ]:
arr.argmax()

In [ ]:
arr.argmin()

---

## Array Attributes

*  You can check the shape and type of a NumPy array using, respectively, the attributes **.shape** and **.dtype**

In [ ]:
arr = np.arange(start=1,stop=11,step=1).reshape(5,2)

print(
    f"* Array:\n {arr} \n\n"
    f"* Array shape: \n {arr.shape} \n\n"
    f"* Array type: \n {arr.dtype}"
    )

---

## Exercises

### 1

* Define the numpy seed=1.
* In a variable called **arr**, Create a 2-d array, 4 x 4, with random integers, where the lowest value is 1 and the max 100 (inclusive).
* In a print() statement, display the array

In [ ]:
np.random.seed(seed=1)
arr = np.random.randint(low=1,high=101,size=(4,4))
print(arr)

### 2

* Using your NumPy knowledge, and python knowledge with print statment function and displaying variables using f-string, create the following statement:
  * **"The max value for the array is 80 and its index location is 6. The min value for the array is 2 and its index location is 9."**

In [ ]:
print(
    f"The max value for the array is {arr.max()} and its index location is {arr.argmax()}. "
    f"The min value for the array is {arr.min()} and its index location is {arr.argmin()}."
    )

---

# Lesson 02

## Lesson Objectives
* Perform Array Indexing and Selecting


<img src="https://raw.githubusercontent.com/numpy/numpy/181f273a59744d58f90f45d953a3285484c72cba/branding/logo/primary/numpylogo.svg" width="25%" height="25%" />

---

## Import Package

* Colab offers a session with a set of packages already installed. To check which packages are installed type in a code cell **!pip freeze** and run it. In case NumPy is not installed, you may type and run in a code cell **!pip install numpy**
* NumPy should be already incluced in this set of packages. You will just need to import it.

In [ ]:
import numpy as np

---

## Python lists vs Numpy Arrays

* **Why not using python lists instead of these NumPy arrays?**

  * Python lists can store elements of various types, like numbers, texts or date for example. 
  * These lists are essentially an array of pointers, indicating to a location that has the information related to the information. **Unfortunately, such approach is extremly expensive in terms of memory and computation.**

  ---

    * To get better on it, NumPy arrays has only homogeneous elements (same data type). **This makes it more efficient for manipulating the elements**. 

  ---

    * Imagine now if you have a huge amount of elements, like millions. **NumPy can perform element-wise operations**, a feature not possible using Python list.

    * This is the major aspect on why NumPy arrays are more insteresting than Python lists for performing mathematical operations on a large amount of data.

## Indexing Arrays

* index 1d array
* indexx 2d array
* index 3d array
* negative slicing


### 1-d arrays

* Let's create a simple 1-d array

In [63]:
arr = np.arange(start=0,stop=26,step=2)
arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

* Retrieve a value in a index position
* Remember that the first position in the array is the index 0

In [64]:
arr[8]

16

In [55]:
arr[0]

0

* Retrieve data in a range
    * In the example below, it starts in the index position 1 (inclusive) and go up to index position 5 (exclusive)

In [65]:
arr[1:5]

array([2, 4, 6, 8])

* Get values in a range, it starts at index 0 and go until index 5 (exclusive) 
* Not assigning the position before the ":" indicates to start from 0.

In [66]:
arr[:5]

array([0, 2, 4, 6, 8])

* Similarly when there is no index mention after the ":", it considers until the end
* In this case, it indexes from positon 10 until the end 

In [67]:
arr[10:]

array([20, 22, 24])

---

### 2-d arrays

* Let's consider the 2-d array

In [76]:
np.random.seed(seed=101)
arr = np.random.randint(low=10,high=50,size=(3,5))
arr

array([[41, 21, 27, 16, 33],
       [21, 19, 23, 14, 38],
       [10, 15, 22, 39, 29]])

* Retrieving single element
    * In this case, the row is at index position 1, and column is at index position 0

In [77]:
arr[1,0]

21

* Indexing a full row
  * In this case, the row at index 1

In [78]:
arr[1,:]

array([21, 19, 23, 14, 38])

* Indexing a full column
  * In this case, the columns at index 3

In [79]:
arr[:,3]

array([16, 14, 39])

  * Slice Rows and Columns
    * In this case, rows from zero to 2 (exclusive) and columns from 1 until the end

In [82]:
arr

array([[41, 21, 27, 16, 33],
       [21, 19, 23, 14, 38],
       [10, 15, 22, 39, 29]])

In [80]:
arr[:2,1:]

array([[21, 27, 16, 33],
       [19, 23, 14, 38]])

### 3-d array

* Let's create a 3-d array
  * In this example, imagine if there is 3 arrays, in parallel, of 2x4

In [85]:
np.random.seed(seed=101)
arr = np.random.randint(low=10,high=50,size=(3,2,4))
arr

array([[[41, 21, 27, 16],
        [33, 21, 19, 23]],

       [[14, 38, 10, 15],
        [22, 39, 29, 18]],

       [[39, 44, 18, 29],
        [20, 22, 41, 33]]])

### Negative Slicing

---

## Selecting an array

In [ ]:
np.random.seed(seed=10)
arr = np.random.randint(low=1,high=25,size=15).reshape(3,5)
arr

In [ ]:
arr > 10

In [ ]:
arr[arr>10]

---

# Lesson 03

## Lesson Objectives
* xxxx
* xxxx
* xxxx

<img src="https://raw.githubusercontent.com/numpy/numpy/181f273a59744d58f90f45d953a3285484c72cba/branding/logo/primary/numpylogo.svg" width="25%" height="25%" />

---

## Import Package

* Colab offers a session with a set of packages already installed. To check which packages are installed type in a code cell **!pip freeze** and run it. In case NumPy is not installed, you may type and run in a code cell **!pip install numpy**
* NumPy should be already incluced in this set of packages. You will just need to import it.

In [ ]:
import numpy as np

---

## Operations

In [ ]:
arr = np.random.randint(low=-3,high=25,size=15).reshape(3,5)
arr

In [ ]:
arr + arr


In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
# Just replaced with nan
arr/arr

In [ ]:
1/arr

In [ ]:
arr**3

---

## Universal Functions

In [ ]:
# https://numpy.org/doc/stable/reference/ufuncs.html

In [ ]:
arr = np.random.randint(low=-3,high=25,size=15).reshape(3,5)
arr

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
np.max(arr)

In [ ]:
np.sin(arr)

In [ ]:
np.log(arr)

In [ ]:
np.std(arr)

---

## Extra content: NumPy and Images

In [90]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import misc
im = misc.

In [91]:
from urllib.request import urlopen
# from scipy.misc import imread

url = 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtUPjSSDzevfy47QqVpd8v2Nrt49QNIXeAfE9ntEwYKJtnDZabwg'

with urlopen(url) as file:
    img = misc.imread(file, mode='RGB')

AttributeError: ignored

In [87]:
from scipy import ndimage
from scipy import misc
import urllib2
import cStringIO

url = \
    "https://maps.googleapis.com/maps/api/staticmap?maptype=satellite&" \
    "center=37.530101,38.600062&" \
    "zoom=14&" \
    "size=256x278&" \
    "key=...."

fi = cStringIO.StringIO(urllib2.urlopen(url).read())
image = misc.imread(fi)
image

ModuleNotFoundError: ignored

---

# Exercises

## Lesson Objectives
* xxxx
* xxxx
* xxxx

<img src="https://raw.githubusercontent.com/numpy/numpy/181f273a59744d58f90f45d953a3285484c72cba/branding/logo/primary/numpylogo.svg" width="25%" height="25%" />

---

## Import Package

* Colab offers a session with a set of packages already installed. To check which packages are installed type in a code cell **!pip freeze** and run it. In case NumPy is not installed, you may type and run in a code cell **!pip install numpy**
* NumPy should be already incluced in this set of packages. You will just need to import it.

In [ ]:
import numpy as np

---

In [ ]:
#### Create an array of 10 zeros 
np.zeros(10)

In [ ]:
#### Create an array of 10 ones
np.ones(10)

In [ ]:
#### Create an array of 10 fives
np.ones(10) * 5

In [ ]:
#### Create an array of 10 integers from 10 to 50
np.random.randint(10,50,10)

In [ ]:
#### Create an array of all the even integers from 10 to 50 (including 50)
np.arange(10,51,2)

In [ ]:
#### Create a 3x3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

In [ ]:
#### Create a 3x3 identity matrix
np.eye(3)

In [ ]:
#### Use NumPy to generate a random number between 0 and 1
np.random.rand(1)

In [ ]:
#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
arr = np.random.randn(500)

In [ ]:
import matplotlib.pyplot as plt
plt.hist(x=arr,bins=50);

In [ ]:
#### Create an array of 20 linearly spaced points between 0 and 1:
np.linspace(0,1,20)

In [ ]:
# Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:
mat = np.arange(1,26).reshape(5,5)
mat

In [ ]:
mat[2:,1:]

In [ ]:
mat[:3,1:2]


In [ ]:
#### Get the sum of all the values in mat
np.sum(mat)

In [ ]:
#### Get the standard deviation of the values in mat
np.std(mat)

In [ ]:
#### Get the sum of all the columns in mat
np.sum(mat,0)