# Lesson 01

## Lesson Objectives
* Understand what is NumPy and its **importance** for Data Science
* Experiment with array **builtin methods**
* Use array **methods and attributes**

<img src="https://raw.githubusercontent.com/numpy/numpy/181f273a59744d58f90f45d953a3285484c72cba/branding/logo/primary/numpylogo.svg" width="25%" height="25%" />

* NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
* It is a **Linear Algebra** Library and almost all of the libraries used in Data Science rely on NumPy as one of their main building blocks.

---

## Import Package

* Colab offers a session with a set of packages already installed. To check which packages are installed type in a code cell **!pip freeze** and run it. In case NumPy is not installed, you may type and run in a code cell **!pip install numpy**
* NumPy should be already incluced in this set of packages. You will just need to import it.

In [2]:
import numpy as np

---

## Array

* An **array** is the foundation of NumPy, it is defined as a grid of values, either numbers or not. It comes as vector or matrix, where vector is a 1-d array, and matrix is 2-d (or n dimension) array. A matrix can also have have 1 row x 1 column.
* An array is **useful** because it helps to organize data. With this structure, elements can easily be sorted or searched.
* We can create a 1-d array based on a list:


In [ ]:
my_list = [7,9,88,4621]
my_list

[7, 9, 88, 4621]

In [ ]:
arr = np.array(my_list)
arr

array([   7,    9,   88, 4621])

* In the previous example, please note 1 bracket before the first item. That indicates it is a **1-d array**. 


```
array([   7,    9,   88, 4621])
```



* Just a side note
  * You don't have necessarily to pass the list as a variable at np.array() function, 
  * You can write the list directly if you prefer: np.array([7,9,88,4621])
  * Both create the same array

* An array can **handle** numbers (integer, float etc), strings (text), timestamps (dates).

In [ ]:
my_list = ['text','label_example',55,150,'final_text_example']
arr = np.array(my_list)
arr

* If your list has more than 1 dimension, you can create a **2-d array**, or matrix.
* Please note the 2 brackets before the first item. That indicates it is a 2-d array.


In [ ]:
my_matrix = [[10,80,77],[99,99,99],[0.5,0.6,0.75]]

arr = np.array(my_matrix)
arr

array([[10.  , 80.  , 77.  ],
       [99.  , 99.  , 99.  ],
       [ 0.5 ,  0.6 ,  0.75]])

---

## Built-in methods to generate arrays

* You can **generate data for your arrays** using built-in methods
* You can quickly create an **evenly spaced** array of numbers using np.arange(). 
    * You may provide 3 arguments: the start, stop and step size of values interval. 
    * Stop argument is not inclusive. 
    * Play around with different step to see the effect. You may try effect as 1, 2, and 5.

In [14]:
arr = np.arange(start=1,stop=9,step=1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

* You can also create an **array of zeros**. Just pass the shape of the desired array. The example below has a shape of 2 x 3 and is a 2-d array

In [6]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

* The example below has shape of 2 x 2 x 2 and is a 3-d array of zeros
* Please note the 3 brackets before the first item. That indicates it is a 3-d array.

In [4]:
arr = np.zeros((2,2,2))
arr

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

* You could also create an **array of all ones**. The example below is a 2-d array.

In [ ]:
arr = np.ones((2,5))
arr

* You can also create **identity matrix**, that is a square matrix that has ones along its main diagonal and zeros everywhere else.
* The example below is an identity matrix of shape 4 x 4.

In [5]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

* A similar function tp np.arange() is np.linspace(), but instead of step size, there is stop argument: it takes in the number of samples that need to be retrieved in that interval. 
* You will provide as argument the start, end and how many points you want in between. 

In [ ]:
arr = np.linspace(start=1,stop=50,num=40)
arr

* You can also create an array of a given shape with **random values from 0 to 1** using np.random.rand()
    * The arguments are the shape you are interested

In [15]:
arr = np.random.rand(2,2)  # 2-d array
arr

array([[0.72640051, 0.42732637],
       [0.89059692, 0.04726837]])

In [17]:
arr = np.random.rand(3,5,2) # 3-d array
arr

array([[[0.66779208, 0.64656516],
        [0.93813232, 0.13016231],
        [0.03976609, 0.34609547],
        [0.54656001, 0.65918801],
        [0.91168219, 0.27915102]],

       [[0.14960985, 0.20735737],
        [0.15845885, 0.57890202],
        [0.82021638, 0.67003379],
        [0.37181572, 0.9875794 ],
        [0.94479053, 0.69350144]],

       [[0.48203479, 0.48846626],
        [0.2484288 , 0.26761739],
        [0.63761474, 0.37273247],
        [0.31588401, 0.98885386],
        [0.52144784, 0.47463492]]])

* You can also create random integers setting the interval and size using **np.random.randint()**
  * The arguments for interval are: low (inclusive) and high (exclusive). Size is the output shape, it can be an integer or tuple.

In [18]:
arr = np.random.randint(low=10,high=50,size=5) # 1-d array
arr 

array([28, 22, 21, 43, 14])

In [20]:
arr = np.random.randint(low=250,high=888,size=(4,3)) # 2-d array
arr 

array([[356, 554, 268],
       [762, 643, 427],
       [842, 356, 622],
       [652, 420, 700]])

* You may be interested to generate random values
  * Run the example below multiple times, the values will c

In [30]:
arr = np.random.randint(low=10,high=50,size=5)
arr

array([47, 20, 14, 39, 49])

---

## Array Methods

* You can reshape the array without changing the data within it using  .reshape() method.
  * the example below shows a 1-d array, with shape 40. 

In [23]:
arr = np.random.randint(low=1,high=150,size=40)
arr

array([ 11,  77,  63,  59,   3, 130, 142,  90,   6,  75, 102,  56, 139,
        85,  27,  57,  18,  87,  90,  20,  20,  99,  98, 105, 101,  20,
       104,  58,  26, 116, 102, 144, 121, 141,  69,  53,  99, 118,  99,
        27])

* You can reshape as 4 x 10, transforming into a 2-d array

In [24]:
arr = arr.reshape(4,10)
arr

array([[ 11,  77,  63,  59,   3, 130, 142,  90,   6,  75],
       [102,  56, 139,  85,  27,  57,  18,  87,  90,  20],
       [ 20,  99,  98, 105, 101,  20, 104,  58,  26, 116],
       [102, 144, 121, 141,  69,  53,  99, 118,  99,  27]])

* Min and Max values can be acessed using .min() and .max() methods.

In [ ]:
arr.max()

In [ ]:
arr.min()

* You can determine the index position of the minimum or maximum value in the darray along a particular axis using the argmin() and argmax() methods

In [27]:
arr.argmax()

31

In [28]:
arr.argmin()

4

---

## Array Attributes

In [ ]:
arr.shape  # .shape is a attribute

In [ ]:
arr.dtype

---

## Activities

* Create in the cell below a 4 x 5 array of all the even integers from -6 to 32, including 32. The array should be stored in a variable called **arr**

In [ ]:
arr = np.arange(start=-6,stop=33,step=2).reshape(4,5)
arr

array([[-6, -4, -2,  0,  2],
       [ 4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32]])

* Using your NumPy knowledge, and python knowledge with print statment function and displaying variables using f-string, create the following statement:
  * **"The max value for the array is 32 and its index location is 19. The min value for this array is -6 and its index location is 0."**

In [ ]:
print(
    f"The max value for the array is {arr.max()} and its index location is {arr.argmax()}. "
    f"The min value for the array is {arr.min()} and its index location is {arr.argmin()}."
    )

The max value for the array is 32 and its index location is 19. The min value for the array is -6 and its index location is 0.


---

# Lesson 02

## Lesson Objectives
* xxx
* xxxxx
* xx

<img src="https://raw.githubusercontent.com/numpy/numpy/181f273a59744d58f90f45d953a3285484c72cba/branding/logo/primary/numpylogo.svg" width="25%" height="25%" />

---

## Import Package

* Colab offers a session with a set of packages already installed. To check which packages are installed type in a code cell **!pip freeze** and run it. In case NumPy is not installed, you may type and run in a code cell **!pip install numpy**
* NumPy should be already incluced in this set of packages. You will just need to import it.

In [ ]:
import numpy as np

---

## Array Indexing and Selecting

In [ ]:
#Creating sample array
arr = arr = np.arange(0,21,2)
arr 

In [ ]:
#Get a value at an index
arr[8]

In [ ]:
#Get values in a range
arr[1:5]

In [ ]:
#Get values in a range
arr[:5]

In [ ]:
#Get values in a range
arr[1:]

In [ ]:
#Get values in a range
arr[:]

---

## Broadcast

In [ ]:
arr = np.arange(0,21,2)
slice_of_arr = arr[0:6]
slice_of_arr

In [ ]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

In [ ]:
arr # original array change as well!!!!

# the data is not copied, it was just a view. It helps to save memory

In [ ]:
# to create a independent slice_of_arr you should
arr = arr = np.arange(0,21,2)
slice_of_arr = arr[0:6].copy()
slice_of_arr



In [ ]:
slice_of_arr[:]=99
slice_of_arr  # slice_of_arr was changed

In [ ]:
arr  # original array remains the same

---

## Indexing a 2D array

In [ ]:
arr = np.random.randint(low=10,high=50,size=15).reshape(3,5)
arr

In [ ]:
#Indexing row
arr[1]

In [ ]:
# Getting individual element value
arr[1,0]

In [ ]:
# 2D array slicing rows and columns
arr[:2,1:]

---

## Selecting an array

In [ ]:
np.random.seed(seed=10)
arr = np.random.randint(low=1,high=25,size=15).reshape(3,5)
arr

In [ ]:
arr > 10

In [ ]:
arr[arr>10]

---

# Lesson 03

## Lesson Objectives
* xxxx
* xxxx
* xxxx

<img src="https://raw.githubusercontent.com/numpy/numpy/181f273a59744d58f90f45d953a3285484c72cba/branding/logo/primary/numpylogo.svg" width="25%" height="25%" />

---

## Import Package

* Colab offers a session with a set of packages already installed. To check which packages are installed type in a code cell **!pip freeze** and run it. In case NumPy is not installed, you may type and run in a code cell **!pip install numpy**
* NumPy should be already incluced in this set of packages. You will just need to import it.

In [ ]:
import numpy as np

---

## Operations

In [ ]:
arr = np.random.randint(low=-3,high=25,size=15).reshape(3,5)
arr

In [ ]:
arr + arr


In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
# Just replaced with nan
arr/arr

In [ ]:
1/arr

In [ ]:
arr**3

---

## Universal Functions

In [ ]:
# https://numpy.org/doc/stable/reference/ufuncs.html

In [ ]:
arr = np.random.randint(low=-3,high=25,size=15).reshape(3,5)
arr

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
np.max(arr)

In [ ]:
np.sin(arr)

In [ ]:
np.log(arr)

In [ ]:
np.std(arr)

---

# Lesson 04 - Exercises

## Lesson Objectives
* xxxx
* xxxx
* xxxx

<img src="https://raw.githubusercontent.com/numpy/numpy/181f273a59744d58f90f45d953a3285484c72cba/branding/logo/primary/numpylogo.svg" width="25%" height="25%" />

---

## Import Package

* Colab offers a session with a set of packages already installed. To check which packages are installed type in a code cell **!pip freeze** and run it. In case NumPy is not installed, you may type and run in a code cell **!pip install numpy**
* NumPy should be already incluced in this set of packages. You will just need to import it.

In [ ]:
import numpy as np

---

In [ ]:
#### Create an array of 10 zeros 
np.zeros(10)

In [ ]:
#### Create an array of 10 ones
np.ones(10)

In [ ]:
#### Create an array of 10 fives
np.ones(10) * 5

In [ ]:
#### Create an array of 10 integers from 10 to 50
np.random.randint(10,50,10)

In [ ]:
#### Create an array of all the even integers from 10 to 50 (including 50)
np.arange(10,51,2)

In [ ]:
#### Create a 3x3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

In [ ]:
#### Create a 3x3 identity matrix
np.eye(3)

In [ ]:
#### Use NumPy to generate a random number between 0 and 1
np.random.rand(1)

In [ ]:
#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
arr = np.random.randn(500)

In [ ]:
import matplotlib.pyplot as plt
plt.hist(x=arr,bins=50);

In [ ]:
#### Create an array of 20 linearly spaced points between 0 and 1:
np.linspace(0,1,20)

In [ ]:
# Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:
mat = np.arange(1,26).reshape(5,5)
mat

In [ ]:
mat[2:,1:]

In [ ]:
mat[:3,1:2]


In [ ]:
#### Get the sum of all the values in mat
np.sum(mat)

In [ ]:
#### Get the standard deviation of the values in mat
np.std(mat)

In [ ]:
#### Get the sum of all the columns in mat
np.sum(mat,0)