# Numpy



<img src="https://numpy.org/images/logos/numpy.svg" width="250" height="205" />

* NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

## Import Package

In [2]:
import numpy as np

## Array

* explain

In [6]:
my_list = [1,2,3]
my_list

arr = np.array(my_list)
arr

array([1, 2, 3])

In [14]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix
arr = np.array(my_matrix)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built in methods

In [29]:
arr = np.arange(start=1,stop=9,step=1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
arr = np.zeros((3,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
arr = np.ones((2,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
arr = np.linspace(start=1,stop=50,num=40)
arr

array([ 1.        ,  2.25641026,  3.51282051,  4.76923077,  6.02564103,
        7.28205128,  8.53846154,  9.79487179, 11.05128205, 12.30769231,
       13.56410256, 14.82051282, 16.07692308, 17.33333333, 18.58974359,
       19.84615385, 21.1025641 , 22.35897436, 23.61538462, 24.87179487,
       26.12820513, 27.38461538, 28.64102564, 29.8974359 , 31.15384615,
       32.41025641, 33.66666667, 34.92307692, 36.17948718, 37.43589744,
       38.69230769, 39.94871795, 41.20512821, 42.46153846, 43.71794872,
       44.97435897, 46.23076923, 47.48717949, 48.74358974, 50.        ])

In [25]:
arr = np.random.rand(2,2)
arr

array([[0.12621896, 0.46737409],
       [0.52704923, 0.11280501]])

In [27]:
arr = np.random.randint(low=10,high=50,size=5)
arr 

array([32, 12, 39, 35, 39])

## Methods

In [40]:
arr = np.random.randint(low=1,high=150,size=40)
arr

array([ 31, 131, 129,  34, 135,  26,  59,  68, 121, 134, 109,  46, 129,
        82,  34,  48,  70,  24,  87, 124, 142, 120, 124,  43,  51,   2,
        65, 108,  17,   7,  25,  51,  91,   9,  44,   8, 107, 105, 103,
        67])

In [41]:
arr.reshape(4,10)

array([[ 31, 131, 129,  34, 135,  26,  59,  68, 121, 134],
       [109,  46, 129,  82,  34,  48,  70,  24,  87, 124],
       [142, 120, 124,  43,  51,   2,  65, 108,  17,   7],
       [ 25,  51,  91,   9,  44,   8, 107, 105, 103,  67]])

In [42]:
arr.max()

142

In [43]:
arr.argmax()

20

In [44]:
arr.min()

2

In [45]:
arr.argmin()

25

## Attributes

In [46]:
arr.shape  # .shape is a attribute

(40,)

In [47]:
arr.dtype

dtype('int64')


Numpy
np.array() : cast list into a array, cast a list of list to make a matrix (2d array)
np.arange(start,stop,step)
.shape
.dtype
np.zeros((row,col))
np.ones((row,col))
np.linspace(start,stop,n_points)
np.eye(diagonal)
np.random.rand(2,2) or (2)  (unif distribution)
np.random.randint(min,max,n_points)
.reshape()
.max()
.min()
argmax() - index location
argmin()
argmax() index location of max
argmin()
slice notation to pickup elements  arr[8]  arr[1:5] arr[:7,4:], arr[:,
broadcast - copy and reference of array  .copy()

numpy.where(condition[, x, y]) - Return elements chosen from x or y depending on condition
np.select()
arr_2d[:2,1:]
conditional selection  arr>5 (bool arr, used as index selection)  arr[arr>5]
math operations with array (+ - * /  **2  )  np.sqrt , np.exp(), np.sin(), np.log()   ufunc on numpy doc